ALM/urls.py
from django.contrib import admin
from django.urls import path,include
from account import views
from django.conf import settings


urlpatterns = [
    path('', views.login, name='login'),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('lead/',include('project.urls')),
]

account/urls.py
from django.urls import path, include
from . import views

app_name ='account'
urlpatterns =[
path('logout/',views.logout, name='logout'),

path('myAccount/',views.myAccount, name='myAccount'),
path('admindashboard/',views.admindashboard, name='admindashboard'),
path('userdashboard/',views.agentdashboard, name='agentdashboard'),


path('forgot_password/', views.forgot_password, name='forgot_password'),
path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
path('reset_password/', views.reset_password, name='reset_password'),

]

account/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.signals import post_save, pre_save
from project.models import Province
from django.contrib.auth import get_user_model
from project.models import Company,Officer

# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, phone_number, password=None, role=None):
        if not phone_number:
            raise ValueError('The Phone Number field must be set')

        user = self.model(phone_number=phone_number, role=role)
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self, phone_number, password=None):
        # Create and save a new superuser with the given phone number and password
        user = self.create_user(phone_number, password)
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user
    
class User(AbstractBaseUser):
    ADMIN = 1
    AGENT = 2

    ROLE_CHOICES = (
        (ADMIN, 'ADMIN'),
        (AGENT, 'AGENT'),
    )
    phone_number = models.CharField(max_length=50,unique=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, blank=True, null=True)
    full_name = models.CharField(max_length=50,blank=True)
    email = models.EmailField(max_length=100, unique=False, default="")
    
    created_date = models.DateTimeField(default=timezone.now)
    modified_date = models.DateTimeField(auto_now=True)
    date_joined = models.DateTimeField(auto_now=True)
    
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = "phone_number"
    objects = UserManager()

    def __str__(self):
        return str(self.full_name)

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    def get_role(self):
        if self.role == 1:
            user_role = 'ADMIN'
        elif self.role == 2:
            user_role = 'AGENT'
        return user_role
    

User = get_user_model()

class ProvinceAdmin(models.Model):
    admin = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        limit_choices_to={'role': User.ADMIN}
    )
    province = models.OneToOneField(Province, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.admin}, {self.province}"


class Action(models.Model):
    company = models.ForeignKey('project.Company', on_delete=models.CASCADE)
    officer = models.ForeignKey('project.Officer', on_delete=models.CASCADE)
    date = models.DateField()
    description = models.TextField()
    admin = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'role': User.ADMIN}, verbose_name='Admin User')

    def __str__(self):
        return f"{self.date} - {self.company} - {self.officer} - {self.admin}"

    class Meta:
        verbose_name_plural = 'Actions'

project/models.py
from django.db import models


class Province(models.Model):
    name = models.CharField(max_length=100 )

    def __str__(self):
        return self.name

class District(models.Model):
    name = models.CharField(max_length=100)
    province = models.ForeignKey(Province, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"

class Municipality(models.Model):
    name = models.CharField(max_length=100)
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class SubCategory(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Company(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE)
    website = models.URLField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class Officer(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='officers')
    designation = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    office = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return f"{self.name}, {self.designation}"

class Newspaper(models.Model):
    name = models.CharField(max_length=100)
    TYPE_CHOICES = (
        ('National', 'National'),
        ('Provincial', 'Provincial'),
        ('Local', 'Local'),
    )
    type = models.CharField(max_length=100, choices=TYPE_CHOICES)
    
    LEVEL_CHOICES =(
        ('A','A'),
        ('B','B'),
        ('C','C')
    ) 
    level = models.CharField(max_length=100, choices=LEVEL_CHOICES)
    front_bw = models.FloatField(default=0.0)
    front_color = models.FloatField(default=0.0)
    inside_bw = models.FloatField(default=0.0)
    inside_color = models.FloatField(default=0.0)
    back_bw = models.FloatField(default=0.0)
    back_color = models.FloatField(default=0.0)
    
    def __str__(self):
        return self.name
    
class Advs(models.Model):
    company = models.ForeignKey('Company', on_delete=models.CASCADE)
    newspaper = models.ForeignKey('Newspaper', on_delete=models.CASCADE)
    publish_date = models.DateField()
    size = models.FloatField()
    caption = models.CharField(max_length=255)  
    adv_type = models.CharField(max_length=255) 
    balance = models.FloatField(default=False , null=True)
    
    def __str__(self):
        return f"{self.company} - {self.newspaper} - {self.publish_date}"








    

project/forms.py
from django import forms
from .models import Advs, Newspaper, Company,Category,SubCategory,Province,Municipality,District,Officer
from account.models import Action

class NewspaperForm(forms.ModelForm):
    class Meta:
        model = Advs
        fields = ['company', 'newspaper', 'publish_date', 'caption','size']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


        # Set newspaper and company fields as dropdowns
        self.fields['newspaper'] = forms.ModelChoiceField(queryset=Newspaper.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
        self.fields['company'] = forms.ModelChoiceField(queryset=Company.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))

        # Set publish_date as DateInput
        self.fields['publish_date'] = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))

        # Set caption as CharField
        self.fields['caption'] = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
        self.fields['size'] = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control','step': 'any', 'min': '0'}))
        
        # Set dropdowns for Page and Color/BW
        page_choices = [('front', 'Front'), ('inside', 'Inside'), ('back', 'Back')]
        color_bw_choices = [('color', 'Color'), ('bw', 'B/W')]

        self.fields['page'] = forms.ChoiceField(choices=page_choices, widget=forms.Select(attrs={'class': 'form-control'}), required=True, label='Page')
        self.fields['color_bw'] = forms.ChoiceField(choices=color_bw_choices, widget=forms.Select(attrs={'class': 'form-control'}), required=True, label='Color/BW')

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name', 'category', 'sub_category', 'province', 'district', 'municipality', 'website', 'address']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Customize the widgets and add additional attributes as needed
        self.fields['name'].widget = forms.TextInput(attrs={'class': 'form-control'})
        self.fields['category'].widget = forms.Select(attrs={'class': 'form-control'})
        self.fields['sub_category'].widget = forms.Select(attrs={'class': 'form-control'})
        self.fields['province'].widget = forms.Select(attrs={'class': 'form-control'})
        self.fields['district'].widget = forms.Select(attrs={'class': 'form-control'})
        self.fields['municipality'].widget = forms.Select(attrs={'class': 'form-control'})
        self.fields['website'].widget = forms.URLInput(attrs={'class': 'form-control'})
        self.fields['address'].widget = forms.Textarea(
            attrs={'class': 'form-control', 'rows': 3,}
        )


        # Add queryset to category field
        self.fields['category'].queryset = Category.objects.all()

        # Add queryset to sub_category field
        self.fields['sub_category'].queryset = SubCategory.objects.all()

        # Add queryset to province field
        self.fields['province'].queryset = Province.objects.all()
                
        self.fields['district'].queryset = District.objects.none()
        
        if 'province' in self.data:
            try:
                province_id = int(self.data.get('province'))
                self.fields['district'].queryset = District.objects.filter(province_id=province_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['district'].queryset = self.instance.province.district_set.order_by('name')
        
        self.fields['municipality'].queryset = Municipality.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['municipality'].queryset = Municipality.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['municipality'].queryset = self.instance.district.municipality_set.order_by('name')

        
        
class PaperForm(forms.ModelForm):
    TYPE_CHOICES = (
        ('National', 'National'),
        ('Provincial', 'Provincial'),
        ('Local', 'Local'),
    )
    LEVEL_CHOICES = (
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
    )

    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    type = forms.ChoiceField(choices=TYPE_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    level = forms.ChoiceField(choices=LEVEL_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    front_bw = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control', 'step': 'any', 'min': '0'}))
    front_color = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control', 'step': 'any', 'min': '0'}))
    inside_bw = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control', 'step': 'any', 'min': '0'}))
    inside_color = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control', 'step': 'any', 'min': '0'}))
    back_bw = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control', 'step': 'any', 'min': '0'}))
    back_color = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control', 'step': 'any', 'min': '0'}))


    class Meta:
        model = Newspaper
        fields = ['name', 'type', 'level', 'front_bw', 'front_color', 'inside_bw', 'inside_color', 'back_bw', 'back_color']
        

class ActionForm(forms.ModelForm):
    class Meta:
        model = Action
        fields = ['description', 'officer']

    def __init__(self, company, *args, **kwargs):
        super(ActionForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget = forms.Textarea(
            attrs={'class': 'form-control', 'rows': 3}
        )
        self.fields['officer'].widget = forms.Select(attrs={'class': 'form-control'})
        
        # Add queryset to officer field based on the company
        self.fields['officer'].queryset = Officer.objects.filter(company=company)

        
        

        
      
       

templates/add_company.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <!-- Load message -->
    <div id="success-message"></div>
  </div>
</div>
<style>
  #success-message {
    position: fixed;
    bottom: 0;
    right: 20px;
    z-index: 99;
    padding: 10px;
  } 
</style>

<div class="card" style="background-color: #F9E4C8; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.6);">
  <div class="card-body text-black">
    <h4 >
      NEW COMPANY
    </h4>
    <br />
    <form method="POST" action="" id="company-form" data-districts-url="{% url 'get_districts' %}" 
    data-municipalities-url="{% url 'get_municipalities' %}">
      {% csrf_token %}

      <div class="row">
        
        <div class="col-lg-6">
          <div class="form-group">
            <label for="name"><h5>Company Name:</h5></label>
            {{ form.name }}
          </div>

          <div class="form-group">
            <label for="category"><h5>Category:</h5></label>
            {{ form.category }}
          </div>

          <div class="form-group">
            <label for="sub_category"><h5>Sub Category:</h5></label>
            {{ form.sub_category }}
          </div>
          
          <div class="form-group">
            <label for="website"><h5>Website:</h5></label>
            {{ form.website }}
          </div>
          
        </div>
        <div class="col-lg-6">
          <div class="form-group">
            <label for="province"><h5>Province:</h5></label>
            {{ form.province }}
          </div>
          <div class="form-group">
            <label for="district"><h5>District:</h5></label>
            {{ form.district }}
          </div>
          <div class="form-group">
            <label for="municipality"><h5>Municipality:</h5></label>
            {{ form.municipality }}
          </div>
          <div class="form-group">
            <label for="address"><h5>Address:</h5></label>
            {{ form.address }}
          </div>
        </div>
      </div>
      <br />
      <button class="btn btn-warning btn-lg waves-effect waves-light" type="submit">Submit</button>
    </form>
  </div>
  <!-- end card-body-->
</div>
<!-- end card -->

<script>
  $(document).ready(function() {
    // Province change event
    $("#id_province").change(function () {
      const districtUrl = "{% url 'get_districts' %}";
      const provinceId = $(this).val();

      // Fetch districts based on the selected province
      $.ajax({
        url: districtUrl,
        data: {
          'province_id': provinceId
        },
        success: function (data) {
          $("#id_district").html(data);
        },
        error: function (xhr, status, error) {
          console.error(xhr.responseText);
        }
      });
    });

    // District change event
    $("#id_district").change(function () {
      const municipalityUrl = "{% url 'get_municipalities' %}";
      const districtId = $(this).val();

      // Fetch municipalities based on the selected district
      $.ajax({
        url: municipalityUrl,
        data: {
          'district_id': districtId
        },
        success: function (data) {
          $("#id_municipality").html(data);
        },
        error: function (xhr, status, error) {
          console.error(xhr.responseText);
        }
      });
    });

    // Form submission
    $(document).on('submit', '#company-form', function (e) {
      e.preventDefault();
      $.ajax({
        type: 'POST',
        url: '{% url "add_company" %}',
        data: {
          name: $("#id_name").val(),
          category: $("#id_category").val(),
          sub_category: $("#id_sub_category").val(),
          province: $("#id_province").val(),
          district: $("#id_district").val(),
          municipality: $("#id_municipality").val(),
          website: $("#id_website").val(),
          address: $("#id_address").val(),
          csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
        },
        success: function (data) {
          // Update the success message dynamically
          $('#success-message').html('<div class="alert alert-success">Company was added successfully</div>');

          // Reset the form elements
          $('#company-form').trigger('reset');

          // Set a timer to hide the success message after 3 seconds (3000 milliseconds)
          setTimeout(function() {
            $('#success-message').empty(); // Remove the content of the success message
          }, 3000);
        },

        error: function (xhr, textStatus, errorThrown) {
          console.log("Error:", errorThrown);
        }
      });
    });
  });
</script>


{% endblock content %}

templates/add_lead.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <!-- Load message -->
      <div id="success-message"></div>
    </div>
  </div>
  <style>
    #success-message {
      position: fixed;
      bottom: 0;
      right: 20px;
      z-index: 99;
      padding: 10px;
    } 
  </style>
  <style>
    body {
        background-image: url('{% static "img/5.svg" %}');
        background-size: cover;
        background-position: center;
        height: 100vh;
        margin: 0;
    }
</style> 
<div class="card" style="background-color: #F9E4C8; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.6);">
    <div class="card-body text-black">
        <h4>NEW LEAD</h4>
        <br>
        <form method="POST" action="" id="lead-form">
            {% csrf_token %}
            
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="newspaper"> <h5>Newspaper</h5> </label>
                        {{ form.newspaper }}
                    </div>

                    <div class="form-group">
                        <label for="company"><h5>Company</h5></label>
                        {{form.company}}
                    </div>

                    <div class="form-group">
                        <label for="publish_date"><h5>Publish Date</h5></label>
                        {{form.publish_date}}
                    </div>
                    <div class="form-group">
                        <label for="caption"><h5>Caption</h5></label>
                        {{form.caption}}
                    </div>
                </div>
                <div class="col-lg-6">
                    
                    <div class="form-group">
                        <label for="size"><h5>Size</h5></label>
                        {{form.size}}
                    </div>
                    <div class="form-group">
                        <label for="page"><h5>Page</h5></label>
                        {{form.page}}
                    </div>
                    <div class="form-group">
                        <label for="color_bw"><h5>Type</h5></label>
                        {{form.color_bw}}
                    </div>                  
                </div>


            </div>
            <br>
            <button class="btn btn-warning btn-lg waves-effect waves-light" type="submit">Submit</button>
        </form>
    </div> <!-- end card-body-->
   
</div> <!-- end card -->
<script type="text/javascript">
    $(document).on('submit', '#lead-form', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "add_lead" %}',
            data: {
                newspaper: $("#id_newspaper").val(),
                company: $("#id_company").val(),
                publish_date: $("#id_publish_date").val(),
                caption: $("#id_caption").val(),
                size: $("#id_size").val(),
                page: $("#id_page").val(),
                color_bw: $("#id_color_bw").val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function (data) {
              // Update the success message dynamically
              $('#success-message').html('<div class="alert alert-success">Lead was added successfully</div>');
          
              // Reset the form elements
              $('#lead-form').trigger('reset');
          
              // Set a timer to hide the success message after 3 seconds (3000 milliseconds)
              setTimeout(function() {
                  $('#success-message').empty(); // Remove the content of the success message
              }, 3000);
          },
          
            error: function (xhr, textStatus, errorThrown) {
                console.log("Error:", errorThrown);
            }
        });
    });
</script>
{% endblock content %}

templates/add_newspaper.html
{% extends "base.html" %} {% load static %} {% block content %}
<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <!-- Load message -->
    <div id="success-message"></div>
  </div>
</div>
<style>
  #success-message {
    position: fixed;
    bottom: 0;
    right: 20px;
    z-index: 99;
    padding: 10px;
  } 
</style>
<style>
  body {
      background-image: url('{% static "img/5.svg" %}');
      background-size: cover;
      background-position: center;
      height: 100vh;
      margin: 0;
  }
</style> 
<div class="card" style="background-color: #F9E4C8; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.6);">
  <div class="card-body text-black">
    <h4 class="p-1" style="background-color:#F9CF93;">Paper Details</h4>
    <br />
    <form method="POST" action="" id="paper-form">
      {% csrf_token %}

      <div class="row">
        <div class="col-lg-6">
          <div class="form-group">
            <label for="name"> <h5>Newspaper Name:</h5> </label>
            {{ form.name }}
          </div>

          <div class="form-group">
            <label for="type"><h5>Type:</h5></label>
            {{form.type}}
          </div>
          <div class="form-group">
            <label for="level"><h5>Level:</h5></label>
            {{form.level}}
          </div>
          
        </div>
        
      </div>
      <br>
      <h4 class="p-1" style="background-color:#F9CF93;">Paper Rates</h4>
      <div class="row mt-3">
        <div class="col-lg-6">
          
          <br>
          
          <div class="form-group">
            <label for="front_color"><h5>Front color:</h5></label>
            {{form.front_color}}
          </div>
          
          <div class="form-group">
            <label for="inside_color"><h5>Inside Color:</h5></label>
            {{form.inside_color}}
          </div>
          
          <div class="form-group">
            <label for="back_color"><h5>Back color:</h5></label>
            {{form.back_color}}
          </div>
        </div>
        <div class="col-lg-6">
          
          <br>
          <div class="form-group">
            <label for="front_bw"><h5>Front bw:</h5></label>
            {{form.front_bw}}
          </div>
          <div class="form-group">
            <label for="inside_bw"><h5>Inside bw:</h5></label>
            {{form.inside_bw}}
          </div>
          <div class="form-group">
            <label for="back_bw"><h5>Back bw:</h5></label>
            {{form.back_bw}}
          </div>

        </div>
      </div>
      <br />
      <button
        class="btn btn-warning btn-lg waves-effect waves-light"
        type="submit"
      >
        Submit
      </button>
    </form>
  </div>
  <!-- end card-body-->
</div>
<!-- end card -->
<script type="text/javascript">
  $(document).on('submit', '#paper-form', function (e) {
      e.preventDefault();
      $.ajax({
          type: 'POST',
          url: '{% url "add_newspaper" %}',
          data: {
              name: $("#id_name").val(),
              type: $("#id_type").val(),
              level: $("#id_level").val(),
              front_bw: $("#id_front_bw").val(),
              front_color: $("#id_front_color").val(),
              inside_bw: $("#id_inside_bw").val(),
              inside_color: $("#id_inside_color").val(),
              back_bw: $("#id_back_bw").val(),
              back_color: $("#id_back_color").val(),
              csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
          },
          success: function (data) {
            // Update the success message dynamically
            $('#success-message').html('<div class="alert alert-success">Newspaper was added successfully</div>');
        
            // Reset the form elements
            $('#paper-form').trigger('reset');
        
            // Set a timer to hide the success message after 3 seconds (3000 milliseconds)
            setTimeout(function() {
                $('#success-message').empty(); // Remove the content of the success message
            }, 3000);
        },
        
          error: function (xhr, textStatus, errorThrown) {
              console.log("Error:", errorThrown);
          }
      });
  });
</script>
{% endblock content %}

templates/admin_dash.html
{% extends "base.html" %}
{% block content %}
    
   
{% endblock content %}

templates/agent_dash.html
{% extends "base.html" %}
{% block content %}
    
   
{% endblock content %}

templates/alerts2.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} show-notification" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
           <strong>{{message}}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/forgot_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title> Sparrow SOS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="Dashboard" name="description" />
    <meta content="MyraStudio" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static "img/smslogo.ico" %}">

    <!-- App css -->
    <link href="{% static "assets/css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "assets/css/icons.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "assets/css/theme.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "assets/css/icons.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "assets/css/theme.min.css" %}" rel="stylesheet" type="text/css" />

</head>

<body>
 
  <div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="d-flex align-items-center min-vh-100">
                    <div class="w-100 d-block bg-white shadow-lg rounded my-5">
                        <div class="row">
                            <div class="col-lg-5 d-none d-lg-block bg-login rounded-left"></div>
                            <div class="col-lg-7">
                                <div class="p-5">
                                    <div class="text-center mb-5">
                                        <a href="{% url 'login' %}" class="text-dark font-size-22 font-family-secondary">
                                            <img src="{% static "img/smslogo.ico" %}" alt="Custom Icon" class="custom-icon">
                                             <b>Sparrow SOS</b>
                                        </a>
                                    </div>
                                    <div class="row">
                                      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                          <!-- Load message -->
                                          {% include 'alerts.html' %}
                                      </div>
                                  </div>
                                    <h1 class="h5 mb-1">Reset Password</h1>
                                    <p class="text-muted mb-4">Enter your email address and we'll send you an email with a link to reset your password.</p>
                                    <form action={% url 'account:forgot_password' %} method="POST">
                                      {% csrf_token %}
                                        <div class="form-group">
                                            <label for="exampleInputEmail">Email Address</label>
                                            <input type="email" name="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address">
                                        </div>
                                        <button type="submit" class="btn  btn-block waves-effect waves-light" style="background-color:#dd7e36; color:#fff;"> Send </button>
                                        
                                    </form>

                                    <div class="row mt-5">
                                        <div class="col-12 text-center">
                                            <p class="text-muted">Already have account?  <a href="{% url 'login' %}" class="text-muted font-weight-medium ml-1"><b>Sign In</b></a></p>
                                            
                                        </div> <!-- end col -->
                                    </div>
                                    <!-- end row -->
                                </div> <!-- end .padding-5 -->
                            </div> <!-- end col -->
                        </div> <!-- end row -->
                    </div> <!-- end .w-100 -->
                </div> <!-- end .d-flex -->
            </div> <!-- end col-->
        </div> <!-- end row -->
    </div>
    <!-- end container -->
</div>
<!-- end page -->
      <!-- jQuery  -->
      <script src="{% static 'assets/js/jquery.min.js' %}"></script>
      <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'assets/js/metismenu.min.js' %}"></script>
      <script src="{% static 'assets/js/waves.js' %}"></script>
      <script src="{% static 'assets/js/simplebar.min.js' %}"></script>

    <!-- App js -->
    <script src="{% static 'assets/js/theme.js' %}"></script>

</body>

</html>